package com.voxellight.rt;

/** Actual renderer state, never inferred from the requested controls or log text. */
public record RtBenchmarkState(int width,int height,int spp,boolean realtime,boolean frozen,
        boolean querySupported,boolean compactSupported,boolean ommSupported,boolean serSupported,
        RtExecutionOptions.Visibility visibility,RtExecutionOptions.Queue queue,boolean omm,boolean ser,
        boolean opacityValid,boolean hasOpaque,long terrainSignature,long sceneGeneration,int sections,long sceneBytes,RtExecutionOptions.Direct direct,RtExecutionOptions.SceneUpdate sceneUpdate,RtExecutionOptions.Realtime realtimePolicy,RtExecutionOptions.Shader shader,RtExecutionOptions.Shadow shadow,RtExecutionOptions.World world,RtExecutionOptions.Integrator integrator,RtExecutionOptions.Primary primary,RtExecutionOptions.Cache cache,RtExecutionOptions.Sampling sampling,RtExecutionOptions.Kernel kernel){
    public RtBenchmarkState(int width,int height,int spp,boolean realtime,boolean frozen,
        boolean querySupported,boolean compactSupported,boolean ommSupported,boolean serSupported,
        RtExecutionOptions.Visibility visibility,RtExecutionOptions.Queue queue,boolean omm,boolean ser,
        boolean opacityValid,boolean hasOpaque,long terrainSignature,long sceneGeneration,int sections,long sceneBytes,RtExecutionOptions.Direct direct,RtExecutionOptions.SceneUpdate sceneUpdate,RtExecutionOptions.Realtime realtimePolicy,RtExecutionOptions.Shader shader,RtExecutionOptions.Shadow shadow,RtExecutionOptions.World world,RtExecutionOptions.Integrator integrator,RtExecutionOptions.Primary primary,RtExecutionOptions.Cache cache,RtExecutionOptions.Sampling sampling){this(width,height,spp,realtime,frozen,querySupported,compactSupported,ommSupported,serSupported,visibility,queue,omm,ser,opacityValid,hasOpaque,terrainSignature,sceneGeneration,sections,sceneBytes,direct,sceneUpdate,realtimePolicy,shader,shadow,world,integrator,primary,cache,sampling,RtExecutionOptions.Kernel.PREINTEGRATED);}

    public RtBenchmarkState(int width,int height,int spp,boolean realtime,boolean frozen,
        boolean querySupported,boolean compactSupported,boolean ommSupported,boolean serSupported,
        RtExecutionOptions.Visibility visibility,RtExecutionOptions.Queue queue,boolean omm,boolean ser,
        boolean opacityValid,boolean hasOpaque,long terrainSignature,long sceneGeneration,int sections,long sceneBytes,RtExecutionOptions.Direct direct,RtExecutionOptions.SceneUpdate sceneUpdate,RtExecutionOptions.Realtime realtimePolicy,RtExecutionOptions.Shader shader,RtExecutionOptions.Shadow shadow,RtExecutionOptions.World world,RtExecutionOptions.Integrator integrator){this(width,height,spp,realtime,frozen,querySupported,compactSupported,ommSupported,serSupported,visibility,queue,omm,ser,opacityValid,hasOpaque,terrainSignature,sceneGeneration,sections,sceneBytes,direct,sceneUpdate,realtimePolicy,shader,shadow,world,integrator,RtExecutionOptions.Primary.MONOLITHIC,RtExecutionOptions.Cache.TAIL,RtExecutionOptions.Sampling.OWEN);}
    public RtBenchmarkState(int width,int height,int spp,boolean realtime,boolean frozen,boolean querySupported,boolean compactSupported,boolean ommSupported,boolean serSupported,RtExecutionOptions.Visibility visibility,RtExecutionOptions.Queue queue,boolean omm,boolean ser,boolean opacityValid,boolean hasOpaque,long terrainSignature,long sceneGeneration,int sections,long sceneBytes,RtExecutionOptions.Direct direct,RtExecutionOptions.SceneUpdate sceneUpdate,RtExecutionOptions.Realtime realtimePolicy,RtExecutionOptions.Shader shader,RtExecutionOptions.Shadow shadow,RtExecutionOptions.World world){this(width,height,spp,realtime,frozen,querySupported,compactSupported,ommSupported,serSupported,visibility,queue,omm,ser,opacityValid,hasOpaque,terrainSignature,sceneGeneration,sections,sceneBytes,direct,sceneUpdate,realtimePolicy,shader,shadow,world,RtExecutionOptions.Integrator.WAVEFRONT);}
    public RtBenchmarkState(int width,int height,int spp,boolean realtime,boolean frozen,boolean querySupported,boolean compactSupported,boolean ommSupported,boolean serSupported,RtExecutionOptions.Visibility visibility,RtExecutionOptions.Queue queue,boolean omm,boolean ser,boolean opacityValid,boolean hasOpaque,long terrainSignature,long sceneGeneration,int sections,long sceneBytes,RtExecutionOptions.Direct direct,RtExecutionOptions.SceneUpdate sceneUpdate,RtExecutionOptions.Realtime realtimePolicy,RtExecutionOptions.Shader shader){this(width,height,spp,realtime,frozen,querySupported,compactSupported,ommSupported,serSupported,visibility,queue,omm,ser,opacityValid,hasOpaque,terrainSignature,sceneGeneration,sections,sceneBytes,direct,sceneUpdate,realtimePolicy,shader,RtExecutionOptions.Shadow.EXACT,RtExecutionOptions.World.EXCLUSIVE);}
    public RtBenchmarkState(int width,int height,int spp,boolean realtime,boolean frozen,boolean querySupported,boolean compactSupported,boolean ommSupported,boolean serSupported,RtExecutionOptions.Visibility visibility,RtExecutionOptions.Queue queue,boolean omm,boolean ser,boolean opacityValid,boolean hasOpaque,long terrainSignature,long sceneGeneration,int sections,long sceneBytes,RtExecutionOptions.Direct direct,RtExecutionOptions.SceneUpdate sceneUpdate,RtExecutionOptions.Realtime realtimePolicy){this(width,height,spp,realtime,frozen,querySupported,compactSupported,ommSupported,serSupported,visibility,queue,omm,ser,opacityValid,hasOpaque,terrainSignature,sceneGeneration,sections,sceneBytes,direct,sceneUpdate,realtimePolicy,RtExecutionOptions.Shader.CLEAN);}
    public RtBenchmarkState(int width,int height,int spp,boolean realtime,boolean frozen,boolean querySupported,boolean compactSupported,boolean ommSupported,boolean serSupported,RtExecutionOptions.Visibility visibility,RtExecutionOptions.Queue queue,boolean omm,boolean ser,boolean opacityValid,boolean hasOpaque,long terrainSignature,long sceneGeneration,int sections,long sceneBytes,RtExecutionOptions.Direct direct,RtExecutionOptions.SceneUpdate sceneUpdate){this(width,height,spp,realtime,frozen,querySupported,compactSupported,ommSupported,serSupported,visibility,queue,omm,ser,opacityValid,hasOpaque,terrainSignature,sceneGeneration,sections,sceneBytes,direct,sceneUpdate,RtExecutionOptions.Realtime.FULL);}
    public RtBenchmarkState(int width,int height,int spp,boolean realtime,boolean frozen,boolean querySupported,boolean compactSupported,boolean ommSupported,boolean serSupported,RtExecutionOptions.Visibility visibility,RtExecutionOptions.Queue queue,boolean omm,boolean ser,boolean opacityValid,boolean hasOpaque,long terrainSignature,long sceneGeneration,int sections,long sceneBytes,RtExecutionOptions.Direct direct){this(width,height,spp,realtime,frozen,querySupported,compactSupported,ommSupported,serSupported,visibility,queue,omm,ser,opacityValid,hasOpaque,terrainSignature,sceneGeneration,sections,sceneBytes,direct,RtExecutionOptions.SceneUpdate.OPTIMIZED);}
    public RtBenchmarkState(int width,int height,int spp,boolean realtime,boolean frozen,boolean querySupported,boolean compactSupported,boolean ommSupported,boolean serSupported,RtExecutionOptions.Visibility visibility,RtExecutionOptions.Queue queue,boolean omm,boolean ser,boolean opacityValid,boolean hasOpaque,long terrainSignature,long sceneGeneration,int sections,long sceneBytes){this(width,height,spp,realtime,frozen,querySupported,compactSupported,ommSupported,serSupported,visibility,queue,omm,ser,opacityValid,hasOpaque,terrainSignature,sceneGeneration,sections,sceneBytes,RtExecutionOptions.Direct.LEGACY);}
    public boolean matches(RtBenchmarkPlan.Config config){return config.kernel()==kernel&&config.primary()==primary&&config.cache()==cache&&config.sampling()==sampling&&config.integrator()==integrator&&config.shadow()==shadow&&config.world()==world&&config.shader()==shader&&config.realtimePolicy()==realtimePolicy&&config.sceneUpdate()==sceneUpdate&&config.direct()==direct&&config.visibility()==visibility&&(config.queue()==RtExecutionOptions.Queue.AUTO||config.queue()==queue)&&config.omm()==omm&&config.ser()==ser&&(!config.omm()||opacityValid);}
    public boolean sameWorkload(RtBenchmarkState other){return width==other.width&&height==other.height&&spp==other.spp&&realtime==other.realtime&&terrainSignature==other.terrainSignature;}
}
