"""Deterministic isotropic rough-diffuse hemisphere kernel, no roughness axis.
A/B Oren-Nayar factors remain runtime-exact. Integrate Fresnel radial kernels
and analytical positive-azimuth moments; clipping stays on the reference path.
"""
from pathlib import Path
import math,struct
N=4096
F=33
C=65
def trans(z,eta):
    ct=math.sqrt(1-(1-z*z)/(eta*eta))
    rp=(eta*z-ct)/(eta*z+ct);rs=(z-eta*ct)/(z+eta*ct)
    return 1-.5*(rp*rp+rs*rs)
base=[];rough=[]
for f in range(F):
    root=.1+.4*f/(F-1);eta=(1+root)/(1-root)
    samples=[((j+.5)/N,trans((j+.5)/N,eta)) for j in range(N)]
    base.append((2*sum(z*t for z,t in samples)/N,2*sum(z*z*t for z,t in samples)/N))
    for c in range(C):
        co=max(1e-5,c/(C-1));so=math.sqrt(max(0,1-co*co));v=[0.,0.,0.]
        for z,t in samples:
            si=math.sqrt(1-z*z);g=so*si/max(co,z);w=z*t*g/N
            v[0]+=2/math.pi*w;v[1]+=2/math.pi*w*z;v[2]+=.5*w*si
        rough.append(v)
def rows(typ,values):return ',\n'.join(typ+'('+','.join(f'{v:.10g}' for v in row)+')' for row in values)
s='''#pragma once
// Generated by tools/generate_diffuse_kernel.py: 33 sqrt(F0) x 65 view cosines,
// 4096 radial midpoint samples; azimuth integrated analytically.
'''
s+='#if defined(RT_CPU_FIXTURE) && !defined(RT_KERNEL_ASSET_FIXTURE)\n'
s+='static const float2 DiffuseBaseKernel[33]={\n'+rows('float2',base)+'\n};\n'
s+='static const float3 DiffuseRoughKernel[2145]={\n'+rows('float3',rough)+'\n};\n'
s+='''float2 diffuseBase(uint i){return DiffuseBaseKernel[i];}
float3 diffuseRough(uint i){return DiffuseRoughKernel[i];}
#else
// Reload-owned asset data. No per-invocation constant-array copies.
float2 diffuseBase(uint i){return asfloat(assets.Load2(assets.Load(240)+i*8));}
float3 diffuseRough(uint i){return asfloat(readWords3(assets,assets.Load(240)+33*8+i*12));}
#endif
'''
s+='''float3 diffuseKernel(Material m,float cosine){
    float f=(sqrt(m.f0)-.1)*80,c=clamp(cosine,0,1)*64;
    uint fi=min(31u,uint(f)),ci=min(63u,uint(c));float fx=f-fi,cx=c-ci;
    float2 base=lerp(diffuseBase(fi),diffuseBase(fi+1),fx);
    float3 rough=lerp(lerp(diffuseRough(fi*65+ci),diffuseRough((fi+1)*65+ci),fx),lerp(diffuseRough(fi*65+ci+1),diffuseRough((fi+1)*65+ci+1),fx),cx);
    float s2=m.microfacetAlpha*.25,A=1-.5*s2/(s2+.33),B=.45*s2/(s2+.09);
    float root=sqrt(m.f0),eta=(1+root)/(1-root);
    return (1-fresnelDielectric(cosine,eta))*float3(A*base.x+B*rough.x,A*base.y+B*rough.y,B*rough.z);
}
'''
Path('shaders/rt/common/diffuse_kernel.slang').write_text(s)

resource=Path('src/main/resources/assets/voxellight/rt/diffuse-kernel.bin')
resource.parent.mkdir(parents=True,exist_ok=True)
resource.write_bytes(struct.pack('<4I',0x314b4456,F,C,N)+b''.join(struct.pack('<'+'f'*len(row),*row) for row in base+rough))
